In [1]:
!pip install numpy

In [2]:
# Example 1: Creating arrays and doing basic math

import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

print("Array:", numbers)
print("Add 10:", numbers + 10)
print("Multiply by 2:", numbers * 2)
print("Mean:", np.mean(numbers))

Array: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Mean: 3.0


In [3]:
# Example 2: 2D arrays, slicing, and filtering

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:\n", matrix)
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Values greater than 5:", matrix[matrix > 5])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Second column: [2 5 8]
Values greater than 5: [6 7 8 9]
